using Content.Client.UserInterface.Controls;
using Content.Shared._N14.Pipboy;
using Content.Shared._Shitmed.Targeting;
using Content.Shared.Audio.Jukebox;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Components;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._N14.Pipboy;

[GenerateTypedNameReferences]
public sealed partial class N14PipboyMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager  _entManager = default!;
    [Dependency] private readonly IPrototypeManager _proto    = default!;

    private AudioSystem _audioSystem = default!;

    /// <summary>Entity UID of the Pip-Boy item (set by BUI before open).</summary>
    public EntityUid PipboyEntity;

    // ── Events for BUI ────────────────────────────────────────────────────
    public event Action<string>?   OnAddNote;
    public event Action<int>?      OnDeleteNote;
    public event Action<string>?   OnRadioSongSelected;
    public event Action<bool>?     OnRadioPlayPressed;
    public event Action?           OnRadioStopPressed;
    public event Action<float>?    OnRadioSetTime;
    public event Action<NetEntity>? OnPickupItem;

    // ── State ─────────────────────────────────────────────────────────────
    private int   _activeTab;
    private float _sliderLockTimer;

    private static readonly Color ColHealthy  = Color.FromHex("#00FF00");
    private static readonly Color ColLightly  = Color.FromHex("#ADFF2F");
    private static readonly Color ColSomewhat = Color.FromHex("#FFFF00");
    private static readonly Color ColModerate = Color.FromHex("#FFA500");
    private static readonly Color ColHeavy    = Color.FromHex("#FF4500");
    private static readonly Color ColCritical = Color.FromHex("#FF0000");
    private static readonly Color ColSevered  = Color.FromHex("#8B0000");
    private static readonly Color ColUnknown  = Color.FromHex("#888888");

    public N14PipboyMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _audioSystem = _entManager.System<AudioSystem>();

        // Tabs
        StatsTabBtn    .OnPressed += _ => SwitchTab(0);
        InventoryTabBtn.OnPressed += _ => SwitchTab(1);
        RadioTabBtn    .OnPressed += _ => SwitchTab(2);
        NotesTabBtn    .OnPressed += _ => SwitchTab(3);

        // Notes
        AddNoteButton.OnPressed += _ => TrySubmitNote();
        NoteInput.OnTextEntered += _ => TrySubmitNote();

        // Radio
        RadioPlayButton .OnPressed += _ => OnRadioPlayPressed?.Invoke(true);
        RadioPauseButton.OnPressed += _ => OnRadioPlayPressed?.Invoke(false);
        RadioStopButton .OnPressed += _ => OnRadioStopPressed?.Invoke();

        RadioSlider.OnReleased += _ =>
        {
            OnRadioSetTime?.Invoke(RadioSlider.Value);
            _sliderLockTimer = 0f;
        };
        RadioSlider.OnValueChanged += _ =>
        {
            if (_sliderLockTimer <= 0f)
                _sliderLockTimer = 0.5f;
        };

        MusicList.OnItemSelected += args =>
        {
            var entry = MusicList[args.ItemIndex];
            if (entry.Metadata is string songId)
                OnRadioSongSelected?.Invoke(songId);
        };

        PopulateMusic();
        SwitchTab(0);
    }

    // ── Tab switching ──────────────────────────────────────────────────────

    private void SwitchTab(int tab)
    {
        _activeTab = tab;
        StatsPanel    .Visible = tab == 0;
        InventoryPanel.Visible = tab == 1;
        RadioPanel    .Visible = tab == 2;
        NotesPanel    .Visible = tab == 3;
    }

    // ── Full state update (called by BUI) ─────────────────────────────────

    public void UpdateState(N14PipboyUpdateState state)
    {
        UpdateStats(state);
        UpdateInventory(state);
        UpdateNotes(state);
    }

    // ── Stats tab ─────────────────────────────────────────────────────────

    private void UpdateStats(N14PipboyUpdateState state)
    {
        var maxHp  = (float) state.MaxHp;
        var curHp  = Math.Max(0f, maxHp - (float) state.CurrentDamage);
        HpLabel  .Text = $"ОЗ: {(int) curHp} / {(int) maxHp}";
        CapsLabel.Text = $"⊙ {state.CapsCount}";

        if (state.PlayerEntity.HasValue)
        {
            var uid = _entManager.GetEntity(state.PlayerEntity.Value);
            if (_entManager.EntityExists(uid))
                PlayerSpriteView.SetEntity(uid);
        }

        SetPart(HeadLabel,      "Голова",    TargetBodyPart.Head,      state.BodyParts);
        SetPart(TorsoLabel,     "Торс",      TargetBodyPart.Torso,     state.BodyParts);
        SetPart(LeftArmLabel,   "Л.Рука",    TargetBodyPart.LeftArm,   state.BodyParts);
        SetPart(LeftHandLabel,  "Л.Кисть",   TargetBodyPart.LeftHand,  state.BodyParts);
        SetPart(LeftLegLabel,   "Л.Нога",    TargetBodyPart.LeftLeg,   state.BodyParts);
        SetPart(LeftFootLabel,  "Л.Ступня",  TargetBodyPart.LeftFoot,  state.BodyParts);
        SetPart(RightArmLabel,  "П.Рука",    TargetBodyPart.RightArm,  state.BodyParts);
        SetPart(RightHandLabel, "П.Кисть",   TargetBodyPart.RightHand, state.BodyParts);
        SetPart(RightLegLabel,  "П.Нога",    TargetBodyPart.RightLeg,  state.BodyParts);
        SetPart(RightFootLabel, "П.Ступня",  TargetBodyPart.RightFoot, state.BodyParts);
    }

    private void SetPart(Label label, string name, TargetBodyPart part,
        Dictionary<TargetBodyPart, TargetIntegrity>? parts)
    {
        if (parts == null || !parts.TryGetValue(part, out var integrity))
        {
            label.Text             = $"{name}: —";
            label.FontColorOverride = ColUnknown;
            return;
        }

        var (status, color) = integrity switch
        {
            TargetIntegrity.Healthy           => ("ОК",        ColHealthy),
            TargetIntegrity.LightlyWounded    => ("Лёгкие",    ColLightly),
            TargetIntegrity.SomewhatWounded   => ("Средние",   ColSomewhat),
            TargetIntegrity.ModeratelyWounded => ("Умеренные", ColModerate),
            TargetIntegrity.HeavilyWounded    => ("Тяжёлые",   ColHeavy),
            TargetIntegrity.CriticallyWounded => ("Критич.",   ColCritical),
            TargetIntegrity.Severed           => ("Ампутир.",  ColSevered),
            TargetIntegrity.Dead              => ("Мёртво",    ColSevered),
            TargetIntegrity.Disabled          => ("Откл.",     ColSevered),
            _                                 => ("—",         ColUnknown),
        };

        label.Text             = $"{name}: {status}";
        label.FontColorOverride = color;
    }

    // ── Inventory tab ──────────────────────────────────────────────────────

    private void UpdateInventory(N14PipboyUpdateState state)
    {
        InventoryList.DisposeAllChildren();

        if (state.Items.Count == 0)
        {
            InventoryList.AddChild(new Label { Text = "Инвентарь пуст." });
            return;
        }

        foreach (var item in state.Items)
        {
            var row = new BoxContainer
            {
                Orientation      = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin           = item.IsInBag
                    ? new Thickness(20, 1, 0, 1)   // indented for bag items
                    : new Thickness(0,  2, 0, 2),
            };

            // Status indicator square (in-hand = green, equipped = blue, in-bag = grey)
            var indicatorColor = item.IsInHand  ? new Color(0.2f, 0.8f, 0.2f, 1f)
                               : item.IsEquipped ? new Color(0.2f, 0.5f, 1.0f, 1f)
                               : item.IsInBag    ? new Color(0.5f, 0.5f, 0.5f, 0.6f)
                               : Color.Transparent;

            var indicator = new PanelContainer
            {
                MinWidth  = 12,
                MinHeight = 12,
                Margin    = new Thickness(0, 0, 6, 0),
                VerticalAlignment = VAlignment.Center,
                ToolTip   = item.IsInHand   ? "В руке"
                          : item.IsEquipped ? "Надето"
                          : item.IsInBag    ? "В сумке"
                          : string.Empty,
            };
            indicator.PanelOverride = new StyleBoxFlat { BackgroundColor = indicatorColor };
            row.AddChild(indicator);

            // Item name
            row.AddChild(new Label
            {
                Text             = item.IsInBag ? $"  {item.Name}" : item.Name,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
                FontColorOverride = item.IsInBag ? new Color(0.75f, 0.75f, 0.75f) : null,
            });

            // "В руку" button for items not already in hand
            if (!item.IsInHand)
            {
                var netId = item.ItemId;
                var pickupBtn = new Button
                {
                    Text              = "В руку",
                    MinWidth          = 64,
                    VerticalAlignment = VAlignment.Center,
                    Margin            = new Thickness(4, 0, 0, 0),
                };
                pickupBtn.OnPressed += _ => OnPickupItem?.Invoke(netId);
                row.AddChild(pickupBtn);
            }

            InventoryList.AddChild(row);
        }
    }

    // ── Radio tab ─────────────────────────────────────────────────────────

    private void PopulateMusic()
    {
        MusicList.Clear();
        foreach (var proto in _proto.EnumeratePrototypes<JukeboxPrototype>())
            MusicList.AddItem(proto.Name, metadata: (object) proto.ID);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_sliderLockTimer > 0f)
            _sliderLockTimer -= args.DeltaSeconds;

        if (_activeTab != 2)
            return;

        if (!_entManager.TryGetComponent<N14PipboyComponent>(PipboyEntity, out var pipComp))
            return;

        if (!string.IsNullOrEmpty(pipComp.SelectedSongId)
            && _proto.TryIndex<JukeboxPrototype>(pipComp.SelectedSongId, out var song))
        {
            RadioSongLabel.Text = song.Name;
        }

        var audioStream = pipComp.AudioStream;
        if (audioStream.HasValue
            && _entManager.TryGetComponent<AudioComponent>(audioStream.Value, out var audioComp)
            && !string.IsNullOrEmpty(audioComp.FileName))
        {
            var position = audioComp.PlaybackPosition;
            var length   = (float) _audioSystem.GetAudioLength(audioComp.FileName).TotalSeconds;

            if (_sliderLockTimer <= 0f && length > 0f)
            {
                RadioSlider.MaxValue = length;
                RadioSlider.SetValueWithoutEvent(Math.Min(position, length));
            }

            RadioDurationLabel.Text = $"{FormatTime(position)} / {FormatTime(length)}";
        }
        else
        {
            RadioDurationLabel.Text = "00:00 / 00:00";
            if (_sliderLockTimer <= 0f)
                RadioSlider.SetValueWithoutEvent(0f);
        }
    }

    private static string FormatTime(float seconds)
    {
        var ts = TimeSpan.FromSeconds(Math.Max(0, seconds));
        return $"{(int) ts.TotalMinutes:D2}:{ts.Seconds:D2}";
    }

    // ── Notes tab ─────────────────────────────────────────────────────────

    private void UpdateNotes(N14PipboyUpdateState state)
    {
        NotesList.DisposeAllChildren();

        for (var i = 0; i < state.Notes.Count; i++)
        {
            var idx  = i;
            var note = state.Notes[i];

            var row = new BoxContainer
            {
                Orientation      = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin           = new Thickness(0, 3),
            };

            row.AddChild(new Label
            {
                Text             = note,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
                ClipText          = false,
            });

            var deleteBtn = new Button
            {
                Text              = "[ УДАЛИТЬ ]",
                MinWidth          = 90,
                VerticalAlignment = VAlignment.Center,
                Margin            = new Thickness(6, 0, 0, 0),
            };
            deleteBtn.OnPressed += _ => OnDeleteNote?.Invoke(idx);
            row.AddChild(deleteBtn);

            NotesList.AddChild(row);
        }

        if (state.Notes.Count == 0)
            NotesList.AddChild(new Label { Text = "Нет заметок." });
    }

    // ── Helpers ───────────────────────────────────────────────────────────

    private void TrySubmitNote()
    {
        var text = NoteInput.Text?.Trim() ?? string.Empty;
        if (string.IsNullOrEmpty(text)) return;
        OnAddNote?.Invoke(text);
        NoteInput.Text = string.Empty;
    }
}
