using Content.Shared._N14.Terminal;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;
namespace Content.Client._N14.Terminal;
[GenerateTypedNameReferences]
public sealed partial class N14TerminalWindow : FancyWindow
{
    private static readonly Color TerminalGreen = Color.FromHex("#33FF33");
    private static readonly Color TerminalGreenDim = Color.FromHex("#1FCC1F");
    private static readonly Color TerminalBg = Color.FromHex("#050F05");
    private static readonly Color TerminalBgSelected = Color.FromHex("#0D2E0D");
    private List<N14TerminalEntry> _categories = new();
    public N14TerminalWindow()
    CategoryList.AddItem(category.CategoryName);
        }
        StyleCategoryList();
        CategoryTitleLabel.Text = "> SELECT CATEGORY";
        ContentLabel.Text = string.Empty;
        {
            CategoryList[0].Selected = true;
            ShowCategory(0);
        }
    }
    private void StyleCategoryList()
    {
        for (var i = 0; i < CategoryList.Count; i++)
        {
            var item = CategoryList[i];
            item.Label.FontColorOverride = TerminalGreenDim;
        }
    }
        var entry = _categories[index];
        CategoryTitleLabel.Text = $"> {entry.CategoryName.ToUpper()}";
        ContentLabel.Text = entry.Content;
        for (var i = 0; i < CategoryList.Count; i++)
        {
            CategoryList[i].Label.FontColorOverride = i == index ? TerminalGreen : TerminalGreenDim;
        }
    }
}
