- type: job
  id: WastelandFarmer
  setPreference: true
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-farmer
  description: job-description-farmer
  playTimeTracker: Farmer
  startingGear: FarmerGear
  icon: "JobIconWastelandFarmer" # Forge-Change
  supervisors: job-supervisors-wastelander
  alwaysUseSpawner: true # Forge-Change
  access:
  - WastelandFarmer
  - TownsPerson # Forge-Change

- type: startingGear
  id: FarmerGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBrahminFarmer
    back: N14ClothingBackpackExplorer # Forge-Change
    shoes: N14ClothingBootsLeather
    outerClothing: ClothingOuterApronBotanist
    belt: ClothingBeltFarmerFilled
    id: N14IDPassportWasteFarmer
  innerClothingSkirt: N14ClothingUniformJumpsuitBrahminFarmer #placeholder
  satchel: N14ClothingBackpackSatchelWastelanderFilled
  duffelbag: N14ClothingBackpackDuffelFilled
  storage: # Forge-Change
    back:
    - N14BoxPlasticFilledWastelander

- type: playTimeTracker
  id: Farmer
